### PR TITLE
access to textarea on review

### PR DESCRIPTION
**Pull request by lecosson**
Related to : https://oat-sa.atlassian.net/browse/TR-117
 
Fix textarea behavior for LTI review mode. When reviewed answer not fit to default size of textarea, scrallbar was inaccesible.
  
#### Related PR's
none

### CODE REVIEW

**Review by jsconan — CHANGES_REQUESTED** [review]
**praise:** The fix is addressing the issue.
**nitpick:** Unfortunately, the solution is not actually correct. Please see the comment underneath.

**suggestion:** a better solution would be to address the issue in a more generic manner, especially since a similar issue exists for other types of interactions. For the scoring, an [alternative set of interaction renderers](https://github.com/oat-sa/tao-item-runner-qti-fe/blob/9a5cdce45d4e45a9bcd731b6c6e25c11704e692f/src/runner/provider/qti.js#L55) has been implemented. It is worth to look at it. 
A quick solution would be to disabled the [CSS overlay](https://github.com/oat-sa/extension-lti-test-review/blob/11fb0c0e11bf96a63ae89cad9d5a4bbd3ec3b87f/views/js/review/component/scss/qtiTestReviewComponent.scss#L43), and to select the `scorer` renderers in the [review provider](https://github.com/oat-sa/extension-lti-test-review/blob/d70a8d4f30cef852a8cdc715dff144af895b696a/views/js/review/provider/qtiTestReviewProvider.js#L295):
```javascript
this.itemRunner = qtiItemRunner(itemData.content.type, itemData.content.data, { assetManager, view: 'scorer' })
```
Of course, a more complete solution would be to add a particular rendering mode for the review (it can be an alias to the scoring mode as long as the implementation remains similar).

**Review by jsconan — COMMENTED** [review]
Looks good.
Do not forget to add a version bump

**Comment by lecosson** [comment]
done

**Review by meefox — APPROVED** [review]

**Review by jsconan — APPROVED** [review]
Looks good.
Is the PR still in draft state?
And could you give a better description of the PR?

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Review by jsconan — APPROVED** [review]

**Pull request merged**
