### PR TITLE
Feature/tr-3072/generate English & Japanese translations

### PR DESCRIPTION
**Pull request by oatymart**
https://oat-sa.atlassian.net/browse/TR-3072

:warning: The extension was never translated before.

- Generated `en-US` and `ja-JP` locales.
- Filled the Japanese using the PO zipfile of 29 November from the ticket. A further update is expected for 7 missing strings (looks like LTI error messages won't be translated now).

Extra locales `ja-UE`, `ja-HS`, `ja-LE` were not created yet (assuming that students don't access Test Review) - **to be checked**.

After adding final Japanese strings, compile by running:
```
php tao/scripts/taoTranslate.php -v -a=compile -e=ltiTestReview -l=ja-JP
```

### CODE REVIEW

**Review by btamas — APPROVED** [review]
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by olga-kulish — COMMENTED** [review]
Works well. I assume they will use this `jp-JP` locale when launching, and not simplified ones. 

But not everything is translated - some keys like 'Total score' are missing. Is it for the next PR?

Screenshot_8

**Comment by btamas** [comment]
> But not everything is translated - some keys like 'Total score' are missing. Is it for the next PR?

I updated translation keys and they are new ones.

**Review by quintanilhar — COMMENTED** [review]
Looks all good! Good job! 👍🏻 

image


- [ ] New code is covered by tests
- [ ] Tests are running successfully on my local machine
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] Feature is working correctly on my local machine
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful
- [X] Pull request's target is not `master`
- [X] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] Commits messages are meaningful
- [X] Commits are atomic
- [ ] Changelog is updated according to changes
- [ ] Documentation is updated according to changes
- [ ] New code is covered by tests
- [ ] Tests are running successfully on my local machine
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] Feature is working correctly on my local machine
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes
- [ ] Documentation is updated according to changes

**Pull request merged**
